# Generated by Django 4.2.2 on 2024-07-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('price', models.FloatField(default=30)),
                ('qty', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
