## Q.21 What is mutable & immutable with example.
'''
What is Mutable?

Mutable objects are those whose value can be changed after creation.
You can modify, update, add, or remove elements without creating a new object.

✔ Examples of Mutable Data Types:

'''
# 1. list
# 2. dictionary
# 3. set


'''
What is Immutable?

Immutable objects are those whose value cannot be changed after creation.
If you try to modify them, Python creates a new object, not change the old one.

✔ Examples of Immutable Data Types:

'''
# 1. string
# 2. tuple
# 3. frozenset


